@echo off
if not exist dist-electron mkdir dist-electron
echo Compiling Electron scripts...
call npx tsc -p tsconfig.electron.json
echo Starting Vite development server...
start /b cmd /c "npx vite --port 5173 --strictPort false"
echo Waiting for Vite server to be ready...
call npx wait-on http://localhost:5173
echo Starting Electron app...
set NODE_ENV=development
call npx electron . --no-sandbox
taskkill /f /im node.exe